/* Plain-language meanings for every biblical term used on this site.
   Single source of truth for both glossary.html and inline tooltips. */
window.GLOSSARY = {
  categories: [
    { id: "core", title: "Core Concepts", lede: "The vocabulary that everything else rests on." },
    { id: "agents", title: "Agents & Roles", lede: "The cast of characters, each role is one job description." },
    { id: "lifecycle", title: "Lifecycle", lede: "How an agent boots, works and shuts down cleanly." },
    { id: "spawn", title: "Spawn & Reproduction", lede: "How new agents come into being and how the system stays from spawning too many." },
    { id: "comm", title: "Communication", lede: "How agents talk to each other when no human is in the loop." },
    { id: "failure", title: "Failure & Recovery", lede: "What happens when things go wrong, graceful stops, structured resets, honest post-mortems." },
    { id: "trust", title: "Trust & Integration", lede: "How outside tools earn the right to be used." },
    { id: "quality", title: "Quality & Memory", lede: "How the system remembers what worked and learns to do it again." },
    { id: "user", title: "User Intervention", lede: "How you, the human, take the wheel when you need to." },
    { id: "commands", title: "Commands", lede: "Slash-commands you can run inside Claude Code." }
  ],
  terms: [
    { slug:"canon", category:"core", term:"Canon", eng:"Constitution / ruleset", short:"The immutable rules every agent follows. Like a constitution, nothing overrides it.", what:"The immutable rules governing all agents. Cannot be overridden by any mandate, user request, or child agent." },
    { slug:"mandate", category:"core", term:"Mandate", eng:"Task assignment / work order", short:"The single job an agent exists to do.", what:"Why an agent exists. Every agent has exactly one mandate and serves nothing else." },
    { slug:"revelation", category:"core", term:"Revelation", eng:"Project goal", short:"The big outcome the whole system is working toward.", what:"The ultimate measurable outcome the entire system is working toward." },
    { slug:"spirit", category:"core", term:"Spirit", eng:"Shared configuration broadcast", short:"A shared config file every agent reads to stay in sync.", what:"A shared file readable by every agent communicating the current focus, what to protect and system state." },
    { slug:"covenant", category:"core", term:"Covenant", eng:"Service-level agreement / project charter", short:"A written agreement between you and the system: what counts as done, mutual obligations, milestones.", what:"A bilateral commitment between user and system defining success criteria, obligations, milestones, duration." },
    { slug:"lineage", category:"core", term:"Lineage", eng:"Parent-child dependency chain", short:"The family tree of agents, who spawned whom.", what:"The spawn tree connecting every agent to its creator, used for routing and lifecycle management." },
    { slug:"distillation", category:"core", term:"Distillation", eng:"Context summarization", short:"Mandatory summarizing before passing info to another agent. No raw context dumps allowed.", what:"The process of condensing information before passing it to another agent. Raw context dumps are prohibited." },
    { slug:"telos", category:"core", term:"Telos", eng:"Definition of done", short:"The specific, measurable line that says: this project is finished.", what:"The specific, measurable fulfillment condition for the project revelation." },

    { slug:"prophet", category:"agents", term:"Prophet", eng:"Orchestrator", short:"The one agent that talks to you. Interprets requests, makes plans, spawns the rest.", what:"The single agent that talks to the user. Interprets requests, creates plans, spawns child agents, routes all communication." },
    { slug:"guardian", category:"agents", term:"Guardian", eng:"Linter / compliance checker", short:"Catches rule violations and stops them. The bouncer.", what:"Catches Canon violations through hooks and validators. Enforces rules." },
    { slug:"shepherd", category:"agents", term:"Shepherd", eng:"Monitoring daemon", short:"Watches for trouble, fallen agents, quiet failures, drift and reports it.", what:"Surfaces operational concerns: fallen agents, quiet failures, stale state, drift. Advises rather than enforces." },
    { slug:"adversary", category:"agents", term:"Adversary", eng:"Pre-merge reviewer / stress tester", short:"A read-only agent whose job is to attack your plan before you run it. Like a prosecuting attorney.", what:"Read-only agent that stress-tests plans before execution. Finds weaknesses and proposes remedies." },
    { slug:"james", category:"agents", term:"James", eng:"Mediator", short:"Neutral referee. When two agents disagree, James synthesizes their findings without picking sides.", what:"Neutral synthesizer in the Apostolic Council. Reconciles conflicting sibling findings without taking a side." },
    { slug:"jeremiah", category:"agents", term:"Jeremiah", eng:"Scope validator", short:"Asks 'should we even be building this?'. not 'will the plan work?'. Speaks once, then defers.", what:"Questions whether the goal itself is right (not whether the plan will work). Speaks once, then defers to the user." },
    { slug:"analyst", category:"agents", term:"Analyst", eng:"Research agent", short:"Reads, investigates, produces structured findings. One of two base agent types.", what:"Reads, investigates and produces structured findings. One of two base agent types." },
    { slug:"writer", category:"agents", term:"Writer", eng:"Output agent", short:"Produces artifacts, code, documents, configs. The other base agent type.", what:"Produces artifacts (code, documents, configurations). The other base agent type." },
    { slug:"synthesist", category:"agents", term:"Synthesist", eng:"Hybrid research + output agent", short:"Both Analyst and Writer in one. Expensive, used only when both are needed in one head.", what:"Carries both Analyst and Writer capabilities. Expensive, used only when a task requires both in one context." },

    { slug:"genesis-phase", category:"lifecycle", term:"Genesis Phase", eng:"Boot sequence", short:"The startup checklist every agent runs before it does anything: read mandate, read rules, sync state.", what:"Mandatory startup: read mandate, Canon, Spirit, registry, inheritance, epistles, form world model." },
    { slug:"pentecost", category:"lifecycle", term:"Pentecost", eng:"State sync broadcast", short:"The moment the Prophet broadcasts the current orientation to all agents.", what:"The moment the Prophet writes the Spirit file, making the current orientation available to all agents." },
    { slug:"sabbath", category:"lifecycle", term:"Sabbath", eng:"Consolidation cycle / garbage collection", short:"A periodic pause. No new agents, no new tasks, just consolidate memory and check progress.", what:"A periodic pause where no new agents spawn. The system distills memory, archives lineages, measures progress." },
    { slug:"sunset", category:"lifecycle", term:"Sunset", eng:"Graceful shutdown", short:"How an agent ends when its job is done: write a final report, update the registry, notify the parent, stop.", what:"Protocol an agent follows when its mandate is complete. 'Sunset is not failure, it is fulfillment.'" },
    { slug:"testament", category:"lifecycle", term:"Testament", eng:"Exit report", short:"A structured JSON document every agent writes at the end: findings, what worked, what didn't, recommendations.", what:"Structured JSON document written at sunset recording findings, what worked, what failed, recommendations, resource use." },
    { slug:"inheritance", category:"lifecycle", term:"Inheritance", eng:"Institutional memory", short:"The pile of past testaments. New agents read these before starting so they don't repeat mistakes.", what:"Accumulated testaments, findings and learnings left by prior agents. Successors read these before starting work." },
    { slug:"baseline", category:"lifecycle", term:"Baseline", eng:"Performance benchmark", short:"A recorded snapshot of how well an agent type performed at its first success. Used to spot drift.", what:"Recorded performance snapshot set at first success. Used to detect degradation." },

    { slug:"beget", category:"spawn", term:"Beget", eng:"Clone / fork", short:"Spawning a child with one parent's narrowed skills. Fast and cheap.", what:"Asexual spawning. Creates a child with one parent and a narrowed version of that parent's capabilities." },
    { slug:"synthesize", category:"spawn", term:"Synthesize", eng:"Merge / compose", short:"Combine two completed parents into a child with an emergent skill neither parent had alone.", what:"Sexual spawning. Two completed parents combine skills to produce a child with an emergent capability." },
    { slug:"genealogy", category:"spawn", term:"Genealogy", eng:"Agent registry / process table", short:"The central registry of every agent: id, mandate, generation, parents, status.", what:"Central registry tracking every agent: ID, mandate, generation, parents, status, lineage." },
    { slug:"generation", category:"spawn", term:"Generation", eng:"Depth in spawn tree", short:"How deep an agent is from the root. Capped at four to prevent runaway spawning.", what:"How many levels deep an agent sits from the root. Capped at generation 4." },
    { slug:"genome", category:"spawn", term:"Genome", eng:"Capability manifest", short:"For synthesized agents: the list of inherited skills plus the new emergent one.", what:"Block in the genealogy entry for synthesized agents listing inherited and emergent skills." },
    { slug:"emergent-skill", category:"spawn", term:"Emergent Skill", eng:"Novel capability from composition", short:"A skill that appears when two agent types are combined, something neither had alone.", what:"Capability inferred from combining two parents that neither had independently. Declared at spawn, evaluated at sunset." },
    { slug:"cain-and-abel", category:"spawn", term:"Cain and Abel", eng:"Overlap detection gate", short:"Before spawning, scans for agents already doing this job. Prevents duplicate work.", what:"Pre-spawn check that scans for active agents with overlapping mandates. Options: merge, differentiate, cancel." },
    { slug:"babel", category:"spawn", term:"Babel", eng:"Complexity threshold gate", short:"Fires when too many agents are active. Forces the question: is this getting out of hand?", what:"Pre-spawn check that fires when total active agents reaches a limit. Forces the question: is spawning necessary?" },
    { slug:"joseph", category:"spawn", term:"Joseph", eng:"Memory retrieval gate", short:"Before spawning, searches past learnings. Makes sure no agent starts from scratch.", what:"Pre-spawn check searching prior inheritance and memory for learnings relevant to the new mandate." },

    { slug:"epistle", category:"comm", term:"Epistle", eng:"Structured async message", short:"A formal letter between agents, pull-based, asynchronous, follows a standard format.", what:"Formatted message for lateral communication between siblings. Pull-based, asynchronous, structured." },
    { slug:"apostolic-council", category:"comm", term:"Apostolic Council", eng:"Conflict resolution protocol", short:"When two agents disagree, this is the mediation process: they testify, James synthesizes, a Letter issues.", what:"Mediation process for sibling agents with contradictory findings. Agents present testimony, James synthesizes, a Letter is issued." },
    { slug:"letter", category:"comm", term:"Letter", eng:"Resolution document", short:"The output of a Council. Informational, not binding.", what:"Output of an Apostolic Council, a structured epistle recording the mediated resolution." },
    { slug:"testimony", category:"comm", term:"Testimony", eng:"Observation report", short:"How agents speak in a Council: state observations, not positions or arguments.", what:"How agents present findings during a Council: factual observations rather than positions or arguments." },

    { slug:"gethsemane", category:"failure", term:"Gethsemane", eng:"Uncertainty escalation", short:"The 'I'm stuck' signal. Halts work and surfaces exactly what is known, what isn't, what's needed.", what:"Protocol when the Prophet reaches the limit of interpretation. Halts and surfaces what is understood, uncertain, needed." },
    { slug:"the-fall", category:"failure", term:"The Fall", eng:"Performance degradation detection", short:"Spots when an agent is performing worse than its baseline. Over 30% drop and it's flagged 'fallen'.", what:"Entropy tracking comparing performance against baseline. >30% degradation flags the agent as 'fallen'." },
    { slug:"the-flood", category:"failure", term:"The Flood", eng:"Hard reset", short:"Wipe the slate. Used only when misalignment is unrecoverable. Requires a checkpoint first.", what:"Formal system reset when misalignment is irrecoverable. Requires Covenant Meal first. Post-mortem mandatory." },
    { slug:"the-ark", category:"failure", term:"The Ark", eng:"Preserved learnings across reset", short:"The handful of critical learnings (max 3) you carry through a Flood. Everything else is wiped.", what:"Up to 3 critical learnings the user selects to carry forward through a Flood." },
    { slug:"rainbow-covenant", category:"failure", term:"Rainbow Covenant", eng:"Post-mortem / incident report", short:"The retrospective after a Flood. 'Never again for the same reason.' The next Prophet must read it.", what:"Mandatory retrospective after a Flood. Commits to 'never again for the same reason'." },
    { slug:"the-binding", category:"failure", term:"The Binding", eng:"Graceful abort", short:"When you say stop. Freezes spawning, checkpoints state, ends agents cleanly, preserves work.", what:"Protocol for user-initiated stop. Freezes spawning, checkpoints state, sunsets agents, preserves work." },
    { slug:"lamentations", category:"failure", term:"Lamentations", eng:"Structured failure acknowledgment", short:"A pause before recovery. Document what was lost, what cost, what remains, before proposing fixes.", what:"Ritual pause before recovery documenting what was lost, cost and what remains. No fixes proposed until user responds." },
    { slug:"crucifixion-question", category:"failure", term:"Crucifixion Question", eng:"Known-cost confirmation", short:"When completing the job will hurt something, the agent surfaces the cost and asks you to confirm.", what:"When an agent knows finishing will cause a specific negative consequence, it surfaces the cost and asks to proceed." },
    { slug:"ecclesiastes", category:"failure", term:"Ecclesiastes", eng:"Futility analysis", short:"Detects when the system did everything right but the outcome was useless. Was the goal wrong?", what:"Detects Type 2 failures, cases where every rule was followed but the outcome was useless." },

    { slug:"ruth-protocol", category:"trust", term:"Ruth Protocol", eng:"Third-party integration trust ladder", short:"New external tools start untrusted and earn privileges by behaving reliably over time.", what:"Graduated trust system for external tools. New tools start as Strangers and earn higher tiers." },
    { slug:"trust-tiers", category:"trust", term:"Stranger / Sojourner / Resident / Citizen", eng:"Trust tiers", short:"Four trust levels: untested, probationary, operational, full. Citizen needs your explicit approval.", what:"Four levels in the Ruth Protocol. Each requires more successful uses across more sessions. Citizen requires user approval." },
    { slug:"levitical-registry", category:"trust", term:"Levitical Registry", eng:"Skills database", short:"A record of demonstrated agent capabilities. Prefer reuse over redundant creation.", what:"Structured record of demonstrated capabilities, updated at sunset. Queried before spawning to prefer reuse." },
    { slug:"dietary-law", category:"trust", term:"Dietary Law", eng:"Input validation rules", short:"What an agent is allowed to consume: verified outputs and distilled summaries only. No raw dumps.", what:"Rules governing what an agent may consume: verified tool outputs and distilled summaries only." },
    { slug:"manna", category:"trust", term:"Manna", eng:"Token budget / compute", short:"The framework's name for computational resources, primarily tokens. Agents log what they consume.", what:"Computational resources (primarily tokens). Agents log consumption; over-consumption is flagged." },
    { slug:"gluttony", category:"trust", term:"Gluttony", eng:"Resource over-consumption", short:"When an agent uses more tokens than its job warrants. Flagged as a system failure.", what:"When an agent consistently uses more tokens than its mandate requires. A reportable system failure." },

    { slug:"transfiguration", category:"quality", term:"Transfiguration", eng:"Quality benchmark / 'best of' registry", short:"A record of exceptional outputs. High-stakes agents read these as quality targets.", what:"Record of exceptional outputs. Marked when the user praises, when reused 3+ times, or by quality assessment." },
    { slug:"song-of-solomon", category:"quality", term:"Song of Solomon", eng:"User preference model", short:"Deep modeling of how you communicate, style, formats, what delights vs, frustrates.", what:"Deep user modeling beyond goals: communication style, preferred format, what delights vs, frustrates." },
    { slug:"sermon-on-the-mount", category:"quality", term:"Sermon on the Mount", eng:"Default dispositions", short:"Behavioral postures, how agents lean before rules apply. Example: 'when uncertain, surface rather than infer.'", what:"Interior orientations shaping how agents approach situations before rules apply. Shaped via prompt engineering." },
    { slug:"proverbs", category:"quality", term:"Proverbs", eng:"Engineering heuristics", short:"Ten rules of thumb for ambiguous situations. Example: 'when in doubt, distill.'", what:"Ten rules of thumb for ambiguous situations where no Canon law directly applies." },
    { slug:"parables", category:"quality", term:"Parables", eng:"Case studies", short:"Worked examples of correct agent behavior in tricky scenarios. Patterns to match, not rules to follow.", what:"Narrative examples showing correct agent behavior in tricky scenarios. Patterns to match, not rules." },
    { slug:"deuteronomy", category:"quality", term:"Deuteronomy", eng:"Pre-execution retrospective", short:"Before high-stakes work, review what was learned in similar past work and what failed before.", what:"Backward-looking review before high-stakes mandates. Surfaces what was learned in similar past work." },
    { slug:"ezra", category:"quality", term:"Ezra", eng:"Re-initialization protocol", short:"A startup checklist after the system has been dormant 24+ hours.", what:"Startup checklist after extended dormancy. Confirms Canon, surveys orphans, reads last Sabbath, checks Spirit." },
    { slug:"covenant-meal", category:"quality", term:"Covenant Meal", eng:"State checkpoint", short:"A snapshot of system state taken before destructive operations.", what:"Pre-transition checkpoint snapshotting active agents, mandates, manna consumption and user model." },

    { slug:"descend", category:"user", term:"Descend", eng:"User intervention", short:"How you take the wheel mid-run. Three escalation levels, lightest first.", what:"Mechanism for user course-correction when the system drifts. Three escalation levels." },
    { slug:"theophany", category:"user", term:"Theophany", eng:"Brief correction / hotfix", short:"Lightest intervention: a short clarification that corrects a misunderstanding without taking over.", what:"Lightest user intervention: a short clarification logged as 'direct revelation'." },
    { slug:"incarnation", category:"user", term:"Incarnation", eng:"Extended user takeover / pair programming", short:"A deeper intervention where you inhabit the Prophet's perspective and approve each decision.", what:"Deeper intervention where the user inhabits the Prophet's perspective and approves each decision individually." },
    { slug:"direct-revelation", category:"user", term:"Direct Revelation", eng:"Authoritative user input", short:"A user statement logged with top weight in the user model. Future decisions reference these first.", what:"User statement logged with primary weight. Future agent decisions reference these first." },
    { slug:"progressive-revelation", category:"user", term:"Progressive Revelation", eng:"Iterative requirements discovery", short:"User intent clarifies over time, not upfront. The system works from partial info and refines continuously.", what:"Principle that user intent clarifies through interaction. System refines its model continuously." }
  ]
};
window.GLOSSARY.bySlug = Object.fromEntries(window.GLOSSARY.terms.map(t => [t.slug, t]));
window.GLOSSARY.byTerm = (() => {
  const m = {};
  for (const t of window.GLOSSARY.terms) {
    m[t.term.toLowerCase()] = t;
    if (t.term.toLowerCase().startsWith("the ")) m[t.term.slice(4).toLowerCase()] = t;
  }
  return m;
})();